### ISSUE TITLE
Recursive qml item lookup

### ISSUE THREAD

**Issue by dmurashko-ms** [faaxm/spix#115]
On the large project, it's hard to maintain a consistent object name path. There are a lot of dynamic elements, and there is also potential for a lot of refactoring to be done on the Items hierarchy. 
For this reason, it would be helpful to have a recursive approach. For example, we could add a parameter or create a separate method like "getStringPropertyRecursive" to work with QML items and their unique object names recursively.

**Comment by ctmbl** [comment]
Hi @dmurashko-ms 
I'm not sure I understood your request correctly but Spix *already* look recursively for QML items' name
see [README](https://github.com/faaxm/spix?tab=readme-ov-file#using-spix)
> Spix matches children recursivley, allowing as much flexibility as needed:

It's also a bad habit to use Spix with full path name, because of breakages in case of refactoring as you already mentioned
