### ISSUE TITLE
Sending additional commands after 'quit' command

### ISSUE THREAD

**Issue by RAMAMario** [faaxm/spix#17]
More a theoretical problem than anything else, but if you would send a 'quit' to the application and then enqueue some additional commands, before the quit is processed, what would happen?
I guess it is undefined behavior, crash or deadlock or something, no?

Can we have an additional lock or something to prevent any additional commands after a 'quit' was committed?

**Comment by faaxm** [comment]
When using RPC calls, the server is run in a QObject, `QtQmlBot`. Once the application shuts down, it will destroy that QObject which, in turn, will wait for the server to close down. No events will be dispatched after the `QtQmlBot` is destroyed.

It is perfectly fine to execute events after `quit` and while the QtQmlBot is not yet shut down, as Qt will still be able to receive and enqueue events. They might not be processed though.
It is also possible that UI objects referenced in the test no longer exist, which will lead to Spix reporting errors.

I don't see any crashes happening. There might also be cases where someone has a special usecase and does fancy stuff after the quit event is received. Due to that, I would not introduce any artificial constraints to prevent people from sending any events in any order they see fit. After all, this is a testing library and I would try to assume as little as possible about what people use it for exactly ;)

**Comment by RAMAMario** [comment]
allright
