### ISSUE TITLE
ListView QML

### ISSUE THREAD

**Issue by VictorCorchezFortech** [faaxm/spix#21]
what should be the approach to mouseClick an item from a ListView QML item that uses a model and a delegate?

**Comment by faaxm** [comment]
You might have to wait for #18 to be implemented, so that there is an option to position the mouse more precisely (i.e. not just click in the center, but something like "click 10px from the top of the list").
As an alternative, you could try using key events to move the selection up/down. The `RepeaterLoader` example uses key presses to navigate a combo box.
