### ISSUE TITLE
How to use in combination of Qt Test?

### ISSUE THREAD

**Issue by LuisAyuso** [faaxm/spix#25]
Hi there,

First of all, terrific job with this library, I can not believe that something like this is not part of the standard tooling. 

I have been experimenting with using this tool in combination with a c++ backend, using Gtest.
I ran into all kinds of errors because of the threads spawned outside of Qt control  (I presume GTest runs fixtures in spawned threads).
For my use case, I need some testing framework to report in xml and such. Therefore my own main function is not an option.

Would be possible to combine the Spix test server with a Qt standard test object? 
Is it possible to tell GTest to drop extra threading? 

Cheers

**Comment by faaxm** [comment]
Hi!

Happy to hear you like Spix :-)
Spix itself already spawns a standard thread in which the actual test is executed, so that it runs independently from the UI. However, in my experience, this should not cause any issues with Qt.

Did you already have a look at the GTest example? It sounds to me it does exactly what you are looking for:
https://github.com/faaxm/spix/tree/master/examples/GTest
