### ISSUE TITLE
Double click ?

### ISSUE THREAD

**Issue by AntSion** [faaxm/spix#27]
Hi, first of all, great library ! I was wondering if it was possible to do a double click on a QML component ? I tried doing two successive mouseclick but it does not register as a doubleClick. I also tried with a wait between the two but it also doesn't register.

**Comment by faaxm** [comment]
I haven't tested this myself yet. At first glance, there is no dedicated "QtDoubleClickEvent" that spix could send and Qt itself uses a normal `QtMouseEvent` for double clicks...
Generally it seems that mouse events are somewhat challenging for Spix right now (see #20) and I suspect that there might be some limits as to what spix can simulate by posting events directly into the Qt event queue, rather than going through the operating system.

If you want to experiment to see which events Qt sends for double clicks, you could use the logging event filter from spix `lib/src/Utils/QtEventRecorder` which you can install as a filter as outlined here https://doc.qt.io/qt-5/qobject.html#installEventFilter

**Comment by faaxm** [comment]
Will close this issue, since this can be done with PyAutoGUI and system events now and I don't see a way to simulate a double-click purely by posting the right `QEvent`, which is how the non-PyAutoGUI part of Spix works.
