### ISSUE TITLE
Mouse right click

### ISSUE THREAD

**Issue by RAMAMario** [faaxm/spix#46]
Hi,

I would like to be able to use mouse right click on an item.
It seems to me, that this is currently not possible, yes?

I could do the implementation if you can give me pointers if you would rather have it as a separate command or somehow amalgamated into the existing mouseClick.

Thanks.

**Comment by faaxm** [comment]
Hi,

thank you for looking into this!
I think it could be an extension of the current mouseClick, at least as long as it is a click (mouse down + up) and not a more general mouse button down event.
I would extend the current ClickOnItem command to take a `Events::MouseButton` argument in its constructor and then use that in `execute` instead of the hardcoded `Events::MouseButtons::left`

Constructor is here:
https://github.com/faaxm/spix/blob/a88161b380f0d094d1bc7a0b58175b2c4d1d53b1/lib/src/Commands/ClickOnItem.cpp#L14
and the events constants for mouse buttons are defined here:
https://github.com/faaxm/spix/blob/a88161b380f0d094d1bc7a0b58175b2c4d1d53b1/lib/src/Scene/Events.h#L19

One tricky thing could be as to how to deal with the calls in AnyRpcServer. I would prefer not to break existing tests that don't provide a mouse button argument with their rpc calls (e.g. python scripts)... The rpc calls are registered here:
https://github.com/faaxm/spix/blob/a88161b380f0d094d1bc7a0b58175b2c4d1d53b1/lib/src/AnyRpcServer.cpp#L30

If there is a way to have default arguments when registering the rpc calls, that would be great. Otherwise, there could be a `mouseClickWithButton` call that takes an integer to identify the button.
